#!/usr/bin/env python3
"""Generate Rust-only lookup tables from the frozen C compatibility oracle."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CRATE_SRC = ROOT / "rust" / "crates" / "kindletool" / "src"
HEADER = (ROOT / "KindleTool" / "kindle_tool.h").read_text(encoding="utf-8")
SOURCE = (ROOT / "KindleTool" / "kindle_tool.c").read_text(encoding="utf-8")
TABLE = (ROOT / "KindleTool" / "kindle_table.h").read_text(encoding="utf-8")
CREATE = (ROOT / "KindleTool" / "create.c").read_text(encoding="utf-8")

BASE32 = "0123456789ABCDEFGHJKLMNPQRSTUVWX"


def serial_code(code: int) -> str:
    if code <= 0xFF:
        return f"{code:02X}"
    chars: list[str] = []
    value = code
    while value:
        value, digit = divmod(value, 32)
        chars.append(BASE32[digit])
    return "".join(reversed(chars)).rjust(3, "0")


def family(symbol: str) -> str:
    checks = (
        (("KindleScribeColorSoft",), "ScribeColorSoft"),
        (("KindlePaperWhite6",), "PaperWhite6"),
        (("KindlePaperWhite5",), "PaperWhite5"),
        (("KindlePaperWhite4", "KindlePW4"), "PaperWhite4"),
        (("KindlePaperWhite3", "KindlePW3"), "PaperWhite3"),
        (("KindlePaperWhite2", "KindlePW2"), "PaperWhite2"),
        (("KindleScribe3",), "Scribe3"),
        (("KindleScribe2",), "Scribe2"),
        (("KindleColorSoft",), "ColorSoft"),
        (("KindleBasic5",), "Basic5"),
        (("KindleBasic4",), "Basic4"),
        (("KindleBasic3",), "Basic3"),
        (("KindleBasic2",), "Basic2"),
        (("KindleOasis3",), "Oasis3"),
        (("KindleOasis2",), "Oasis2"),
        (("Kindle5Touch",), "Touch"),
        (("KindleVoyage",), "Voyage"),
        (("KindleScribe",), "Scribe"),
        (("KindlePaperWhite",), "PaperWhite"),
        (("KindleBasic",), "Basic"),
        (("KindleOasis",), "Oasis"),
        (("Kindle4",), "Kindle4"),
    )
    for prefixes, result in checks:
        if symbol.startswith(prefixes):
            return result
    return "Legacy"


def generate_devices() -> None:
    enum_match = re.search(
        r"typedef enum\s*\{\s*Kindle1\s*=\s*0x01,(?P<body>.*?)\}\s*Device;",
        HEADER,
        re.S,
    )
    if enum_match is None:
        raise RuntimeError("Device enum not found")
    body = "Kindle1 = 0x01," + enum_match.group("body")
    entries = re.findall(r"^\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*,?", body, re.M)
    names = dict(re.findall(r'case\s+([A-Za-z_]\w*)\s*:\s*return\s+"([^"]*)"\s*;', SOURCE, re.S))

    family_aliases = {
        "Kindle4": "kindle4",
        "Touch": "touch",
        "PaperWhite": "paperwhite",
        "PaperWhite2": "paperwhite2",
        "Basic": "basic",
        "Voyage": "voyage",
        "PaperWhite3": "paperwhite3",
        "Oasis": "oasis",
        "Basic2": "basic2",
        "Oasis2": "oasis2",
        "PaperWhite4": "paperwhite4",
        "Basic3": "basic3",
        "Oasis3": "oasis3",
        "PaperWhite5": "paperwhite5",
        "Basic4": "basic4",
        "Scribe": "scribe",
        "Basic5": "basic5",
        "PaperWhite6": "paperwhite6",
        "Scribe2": "scribe2",
        "ColorSoft": "colorsoft",
        "Scribe3": "scribe3",
        "ScribeColorSoft": "scribecolorsoft",
    }
    alias_matches = list(
        re.finditer(r'strcasecmp\s*\(\s*optarg\s*,\s*"([^"]+)"\s*\)', CREATE)
    )
    alias_bodies: dict[str, str] = {}
    for index, match in enumerate(alias_matches):
        end = alias_matches[index + 1].start() if index + 1 < len(alias_matches) else len(CREATE)
        alias_bodies.setdefault(match.group(1).lower(), CREATE[match.start() : end])

    family_order: dict[str, int] = {}
    gated_symbols: set[str] = set()
    for family_name, alias in family_aliases.items():
        body = alias_bodies.get(alias, "")
        assignments = list(
            re.finditer(r"info\.devices\[info\.num_devices\+\+\]\s*=\s*([A-Za-z_]\w*)\s*;", body)
        )
        gate = body.find("if (kt_with_unknown_devcodes)")
        for order, assignment in enumerate(assignments):
            symbol = assignment.group(1)
            family_order[symbol] = order
            if gate >= 0 and assignment.start() > gate:
                gated_symbols.add(symbol)

    lines = [
        "// @generated by rust/tools/generate_legacy_tables.py; do not edit by hand.",
        "pub(crate) static DEVICE_CATALOG: &[DeviceRecord] = &[",
    ]
    seen: set[int] = set()
    for symbol, raw_code in entries:
        code = int(raw_code, 0)
        if symbol == "KindleUnknown" or code in seen:
            continue
        seen.add(code)
        label = names.get(symbol, f"Unknown Kindle ({serial_code(code)})")
        unknown = "Unknown" in symbol or symbol.startswith("ValidKindleUnknown")
        record_family = family(symbol)
        lines.append(
            "    DeviceRecord { "
            f"code: DeviceCode(0x{code:04X}), symbol: {json.dumps(symbol)}, "
            f"serial: {json.dumps(serial_code(code))}, name: {json.dumps(label)}, "
            f"family: DeviceFamily::{record_family}, "
            f"family_order: {family_order.get(symbol, 65535)}, "
            f"unknown: {str(unknown).lower()}, "
            f"requires_unknown_flag: {str(symbol in gated_symbols).lower()} "
            "},"
        )
    lines.append("];\n")
    (CRATE_SRC / "devices_generated.rs").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def generate_tables() -> None:
    lines = ["// @generated by rust/tools/generate_legacy_tables.py; do not edit by hand."]
    for name in ("ptog", "gtop"):
        match = re.search(rf"static const uint8_t {name}\[\]\s*=\s*\{{(.*?)\}};", TABLE, re.S)
        if match is None:
            raise RuntimeError(f"{name} table not found")
        values = re.findall(r"0x[0-9A-Fa-f]{2}", match.group(1))
        if len(values) != 256:
            raise RuntimeError(f"{name} contains {len(values)} values")
        rust_name = name.upper()
        lines.append(f"pub(crate) const {rust_name}: [u8; 256] = [")
        for offset in range(0, 256, 16):
            lines.append("    " + ", ".join(values[offset : offset + 16]) + ",")
        lines.append("];\n")
    (CRATE_SRC / "tables_generated.rs").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def generate_default_key() -> None:
    match = re.search(r"sign_key_sexp\[\].*?=\s*\{(.*?)\};", CREATE, re.S)
    if match is None:
        raise RuntimeError("default key not found")
    sexp = bytes(int(value, 16) for value in re.findall(r"0x([0-9A-Fa-f]{2})", match.group(1)))
    lines = ["// @generated by rust/tools/generate_legacy_tables.py; do not edit by hand."]
    for field in "nedpq":
        item = re.search(rb"\(1:" + field.encode() + rb"(\d+):", sexp)
        if item is None:
            raise RuntimeError(f"default key field {field} not found")
        length = int(item.group(1))
        value = sexp[item.end() : item.end() + length]
        lines.append(f'pub(crate) const RSA_{field.upper()}: &str = "{value.hex()}";')
    lines.append("")
    (CRATE_SRC / "key_generated.rs").write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    CRATE_SRC.mkdir(parents=True, exist_ok=True)
    generate_devices()
    generate_tables()
    generate_default_key()
